import type { Project } from "@/app/portfolio/page";

export const projects: Project[] = [
  { 
    id: "1", 
    title: "Cultural Poster", 
    category: "posters", 
    featured: true,
    type: 'image',
    image: "/images/kannan.png",
  },
  { 
    id: "2", 
    title: "Business Branding", 
    category: "posters", 
    featured: true,
    type: 'image',
    image: "/images/kannan3.jpeg",
  },
  { 
    id: "3", 
    title: "Car Design", 
    category: "design", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  { 
    id: "4", 
    title: "Kannan VFX 2", 
    category: "posters", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  { 
    id: "5", 
    title: "Ethereal Landscapes", 
    category: "vfx", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  { 
    id: "6", 
    title: "Retro Revival", 
    category: "posters", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  { 
    id: "7", 
    title: "Particle Symphony", 
    category: "motion", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  { 
    id: "8", 
    title: "Cybernetic Dreams", 
    category: "vfx", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  { 
    id: "9", 
    title: "Minimal Expressions", 
    category: "posters", 
    featured: false,
    type: 'image',
    image: "/placeholder.svg?height=450&width=600",
  },
  {
    id: "10",
    title: "VFX Demo Reel",
    category: "vfx",
    featured: true,
    type: 'youtube',
    videoId: "KBNey4upFKE"
  },
  {
    id: "11",
    title: "VFemo",
    category: "vfx",
    featured: true,
    type: 'youtube',
    videoId: "AhDD4c4B9u4"
  },
  {
    id: "12",
    title: "VFXo",
    category: "vfx",
    featured: true,
    type: 'youtube',
    videoId: "ilL7RQIYxuQ"
  },
];
